# Generated by Django 5.0.1 on 2024-01-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_location_city_location_state_location_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
            ),
        ),
    ]
