# Generated by Django 5.0.1 on 2024-01-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_location_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.location",
            ),
        ),
    ]
