# Generated by Django 5.0.1 on 2024-03-25 01:19

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=users.utils.user_directory_path
            ),
        ),
    ]
