# Generated by Django 5.0.1 on 2024-04-11 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Location",
            new_name="location",
        ),
    ]
