# Generated by Django 5.0.1 on 2024-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_location_profile_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="zipcode",
            new_name="zip_code",
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
